<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use App\Http\Requests\Auth\LoginRequest; // This request class is also typically generated by Breeze/UI
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\View\View;

class AuthenticatedSessionController extends Controller
{
    /**
     * Display the login view.
     * Requires a view: resources/views/auth/login.blade.php
     */
    public function create(): View
    {
        // Ensure you have a view at resources/views/auth/login.blade.php
        return view("auth.login");
    }

    /**
     * Handle an incoming authentication request.
     */
    public function store(LoginRequest $request): RedirectResponse
    {
        // Authenticate the user based on the LoginRequest validation
        $request->authenticate();

        // Regenerate the session ID to prevent session fixation
        $request->session()->regenerate();

        // Redirect the user to their intended destination or the dashboard
        // The redirect()->intended() method redirects to the URL the user was
        // trying to access before being intercepted by the authentication middleware,
        // or falls back to the dashboard route.
        return redirect()->intended(route("dashboard", absolute: false));
    }

    /**
     * Destroy an authenticated session (logout).
     */
    public function destroy(Request $request): RedirectResponse
    {
        // Log the user out of the specified guard (default is 'web')
        Auth::guard("web")->logout();

        // Invalidate the current session
        $request->session()->invalidate();

        // Regenerate the CSRF token
        $request->session()->regenerateToken();

        // Redirect the user to the homepage
        return redirect("/");
    }
}

